---
- name: Manage templates
  community.zabbix.zabbix_template:
    clear_templates: "{{ item.clear_templates | default(omit) }}"
    http_login_password: "{{ zabbix_config_login_user | default(omit) }}"
    http_login_user: "{{ zabbix_config_login_password | default(omit) }}"
    link_templates: "{{ item.link_templates | default(omit) }}"
    macros: "{{ item.macros | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    tags: "{{ item.tags | default(omit) }}"
    template_groups: "{{ item.template_groups | default(omit) }}"
    template_json: "{{ item.template_json | default(omit) }}"
    template_name: "{{ item.template_name | default(omit) }}"
    template_xml: "{{ item.template_xml | default(omit) }}"
  loop: "{{ zabbix_config_templates }}"
  tags:
    - zabbix_config_templates

- name: Create host groups
  community.zabbix.zabbix_group:
    host_groups: "{{ item }}"
    http_login_password: "{{ zabbix_config_login_user | default(omit) }}"
    http_login_user: "{{ zabbix_config_login_password | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ zabbix_config_host_groups }}"
  tags:
    - zabbix_config_host_groups

- name: Manage zabbix proxies
  community.zabbix.zabbix_proxy:
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    http_login_password: "{{ zabbix_config_login_user | default(omit) }}"
    http_login_user: "{{ zabbix_config_login_password | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    proxy_address: "{{ item.proxy_address | default(omit) }}"
    proxy_name: "{{ item.proxy_name }}"
    state: "{{ item.state | default(omit) }}"
    status: "{{ item.status | default(omit) }}"
    tls_accept: "{{ item.tls_accept | default(omit) }}"
    tls_connect: "{{ item.tls_connect | default(omit) }}"
    tls_psk: "{{ item.tls_psk | default(omit) }}"
    tls_psk_identity: "{{ item.tls_psk_identity | default(omit)}}"
    tls_subject: "{{ item.tls_subject | default(omit) }}"
  loop: "{{ zabbix_config_proxies }}"
  tags:
    - zabbix_config_proxies

- name: Manage hosts
  community.zabbix.zabbix_host:
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    host_groups: "{{ item.host_groups | default(omit) }}"
    host_name: "{{ item.host_name }}"
    http_login_password: "{{ zabbix_config_login_user | default(omit) }}"
    http_login_user: "{{ zabbix_config_login_password | default(omit) }}"
    interfaces: "{{ item.interfaces | default(omit) }}"
    inventory_mode: "{{ item.inventory_mode | default(omit) }}"
    inventory_zabbix: "{{ item.inventory_zabbix | default(omit) }}"
    ipmi_authtype: "{{ item.ipmi_authtype | default(omit) }}"
    ipmi_password: "{{ item.ipmi_password | default(omit) }}"
    ipmi_privilege: "{{ item.ipmi_privilege | default(omit) }}"
    ipmi_username: "{{ item.ipmi_username | default(omit) }}"
    link_templates: "{{ item.link_templates | default(omit) }}"
    macros: "{{ item.macros | default(omit) }}"
    proxy: "{{ item.proxy | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    status: "{{ item.status | default(omit) }}"
    tags: "{{ item.tags | default(omit) }}"
    tls_accept: "{{ item.tls_accept | default(omit) }}"
    tls_connect: "{{ item.tls_connect | default(omit) }}"
    tls_psk: "{{ item.tls_psk | default(omit) }}"
    tls_psk_identity: "{{ item.tls_psk_identity | default(omit) }}"
    tls_subject: "{{ item.tls_subject | default(omit) }}"
    visible_name: "{{ item.visible_name | default(omit) }}"
  loop: "{{ zabbix_config_hosts }}"
  tags:
    - zabbix_config_hosts

- name: Manage user groups
  community.zabbix.zabbix_usergroup:
    debug_mode: "{{ item.debug_mode | default(omit) }}"
    gui_access: "{{ item.gui_access | default(omit) }}"
    hostgroup_rights: "{{ item.hostgroup_rights | default(omit) }}"
    http_login_password: "{{ zabbix_config_login_user | default(omit) }}"
    http_login_user: "{{ zabbix_config_login_password | default(omit) }}"
    name: "{{ item.name }}"
    rights: "{{ item.rights | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    status: "{{ item.status | default(omit) }}"
    tag_filters: "{{ item.tag_filters | default(omit) }}"
    templategroup_rights: "{{ item.templategroup_rights | default(omit) }}"
    userdirectory: "{{ item.userdirectory | default(omit) }}"
  loop: "{{ zabbix_config_usergroups }}"
  tags:
    - zabbix_config_usergroups

- name: Manage media types
  community.zabbix.zabbix_mediatype:
    attempt_interval: "{{ item.attempt_interval | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    event_menu: "{{ item.event_menu | default(omit) }}"
    event_menu_name: "{{ item.event_menu_name | default(omit) }}"
    event_menu_url: "{{ item.event_menu_url | default(omit) }}"
    gsm_modem: "{{ item.gsm_modem | default(omit) }}"
    http_login_password: "{{ zabbix_config_login_user | default(omit) }}"
    http_login_user: "{{ zabbix_config_login_password | default(omit) }}"
    max_attempts: "{{ item.max_attempts | default(omit) }}"
    max_sessions: "{{ item.max_sessions | default(omit) }}"
    message_templates: "{{ item.message_templates | default(omit) }}"
    message_text_limit: "{{ item.message_text_limit | default(omit) }}"
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    process_tags: "{{ item.process_tags | default(omit) }}"
    script_name: "{{ item.script_name | default(omit) }}"
    script_params: "{{ item.script_params | default(omit) }}"
    smtp_authentication: "{{ item.smtp_authentication | default(omit) }}"
    smtp_email: "{{ item.smtp_email | default(omit) }}"
    smtp_helo: "{{ item.smtp_helo | default(omit) }}"
    smtp_security: "{{ item.smtp_security | default(omit) }}"
    smtp_server: "{{ item.smtp_server | default(omit) }}"
    smtp_server_port: "{{ item.smtp_server_port | default(omit) }}"
    smtp_verify_host: "{{ item.smtp_verify_host | default(omit) }}"
    smtp_verify_peer: "{{ item.smtp_verify_peer | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    status: "{{ item.status | default(omit) }}"
    type: "{{ item.type }}"
    username: "{{ item.username | default(omit) }}"
    webhook_params: "{{ item.webhook_params | default(omit) }}"
    webhook_script: "{{ item.webhook_script | default(omit) }}"
    webhook_timeout: "{{ item.webhook_timeout | default(omit) }}"
  loop: "{{ zabbix_config_media_types }}"
  tags:
    - zabbix_config_media_types

- name: Manage user roles
  community.zabbix.zabbix_user_role:
    http_login_password: "{{ zabbix_config_login_user | default(omit) }}"
    http_login_user: "{{ zabbix_config_login_password | default(omit) }}"
    name: "{{ item.name }}"
    rules: "{{ item.rules | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    type: "{{ item.type | default(omit) }}"
  loop: "{{ zabbix_config_user_roles }}"
  tags:
    - zabbix_config_user_roles

- name: Manage users
  community.zabbix.zabbix_user:
    after_login_url: "{{ item.after_login_url | default(omit) }}"
    autologin: "{{ item.autologin | default(omit) }}"
    autologout: "{{ item.autologout | default(omit) }}"
    http_login_password: "{{ zabbix_config_login_user | default(omit) }}"
    http_login_user: "{{ zabbix_config_login_password | default(omit) }}"
    lang: "{{ item.lang | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    override_passwd: "{{ item.override_passwd | default(omit) }}"
    passwd: "{{ item.passwd | default(omit) }}"
    refresh: "{{ item.refresh | default(omit) }}"
    role_name: "{{ item.role_name | default(omit) }}"
    rows_per_page: "{{ item.rows_per_page | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    surname: "{{ item.surname | default(omit) }}"
    theme: "{{ item.theme | default(omit) }}"
    timezone: "{{ item.timezone | default(omit) }}"
    user_medias: "{{ item.user_medias | default(omit) }}"
    username: "{{ item.username }}"
    usrgrps: "{{ item.usrgrps | default(omit) }}"
  loop: "{{ zabbix_config_users }}"
  no_log: true
  tags:
    - zabbix_config_users

- name: Manage actions
  community.zabbix.zabbix_action:
    acknowledge_operations: "{{ item.acknowledge_operations | default(omit) }}"
    conditions: "{{ item.conditions | default(omit) }}"
    esc_period: "{{ item.esc_period | default(omit) }}"
    eval_type: "{{ item.eval_type | default(omit) }}"
    event_source: "{{ item.event_source | default(omit) }}"
    formula: "{{ item.formula | default(omit) }}"
    http_login_password: "{{ zabbix_config_login_user | default(omit) }}"
    http_login_user: "{{ zabbix_config_login_password | default(omit) }}"
    name: "{{ item.name }}"
    operations: "{{ item.operations | default(omit) }}"
    pause_in_maintenance: "{{ item.pause_in_maintenance | default(omit) }}"
    pause_symptoms: "{{ item.pause_symptoms | default(omit) }}"
    recovery_operations: "{{ item.recovery_operations | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    status: "{{ item.status | default(omit) }}"
  loop: "{{ zabbix_config_actions }}"
  tags:
    - zabbix_config_actions

- name: Manage web scenarios
  zabbix_webscenario:
    http_login_password: "{{ zabbix_config_login_user | default(omit) }}"
    http_login_user: "{{ zabbix_config_login_password | default(omit) }}"
    name: "{{ item.name }}"
    host_name: "{{ item.host_name }}"
    steps: "{{ item.steps | default(omit) }}"
    agent: "{{ item.agent | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    delay: "{{ item.delay | default(omit) }}"
    headers: "{{ item.headers | default(omit) }}"
    retries: "{{ item.retries | default(omit) }}"
  loop: "{{ zabbix_config_web_scenarios }}"
  tags:
    - zabbix_config_web_scenarios
