---
- name: Manage templates
  community.zabbix.zabbix_template:
    server_url: "{{ zabbix_config_server_url }}"
    login_user: "{{ zabbix_config_login_user }}"
    login_password: "{{ zabbix_config_login_password }}"
    clear_templates: "{{ item.clear_templates | default(omit) }}"
    dump_format: "{{ item.dump_format | default(omit) }}"
    link_templates: "{{ item.link_templates | default(omit) }}"
    macros: "{{ item.macros | default(omit) }}"
    omit_date: "{{ item.omit_date | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    template_groups: "{{ item.template_groups | default(omit) }}"
    template_json: "{{ item.template_json | default(omit) }}"
    template_name: "{{ item.template_name | default(omit) }}"
    template_xml: "{{ item.template_xml | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
  loop: "{{ zabbix_config_templates }}"
  tags:
    - zabbix_config_templates

- name: Create host groups
  community.zabbix.zabbix_group:
    server_url: "{{ zabbix_config_server_url }}"
    login_user: "{{ zabbix_config_login_user }}"
    login_password: "{{ zabbix_config_login_password }}"
    state: present
    host_groups: "{{ item }}"
  loop: "{{ zabbix_config_host_groups }}"
  tags:
    - zabbix_config_host_groups

- name: Manage hosts
  community.zabbix.zabbix_host:
    description: "{{ item.description | default(omit) }}"
    host_groups: "{{ item.host_groups | default(omit) }}"
    host_name: "{{ item.host_name }}"
    interfaces: "{{ item.interfaces | default(omit) }}"
    link_templates: "{{ item.link_templates | default(omit) }}"
    login_password: "{{ zabbix_config_login_password }}"
    login_user: "{{ zabbix_config_login_user }}"
    macros: "{{ item.macros | default(omit) }}"
    server_url: "{{ zabbix_config_server_url }}"
    state: "{{ item.state | default(omit) }}"
    status: "{{ item.status | default(omit) }}"
    tags: "{{ item.tags | default(omit) }}"
    visible_name: "{{ item.visible_name | default(omit) }}"
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    proxy: "{{ item.proxy | default(omit) }}"
    tls_accept: "{{ item.tls_accept | default(omit) }}"
    tls_connect: "{{ item.tls_connect | default(omit) }}"
    tls_psk: "{{ item.tls_psk | default(omit) }}"
    tls_psk_identity: "{{ item.tls_psk_identity | default(omit) }}"
    tls_subject: "{{ item.tls_subject | default(omit) }}"
  loop: "{{ zabbix_config_hosts }}"
  tags:
    - zabbix_config_hosts

- name: Manage actions
  zabbix_action:
    server_url: "{{ zabbix_config_server_url }}"
    login_user: "{{ zabbix_config_login_user }}"
    login_password: "{{ zabbix_config_login_password }}"
    name: "{{ item.name }}"
    update_operations: "{{ item.update_operations | default(omit) }}"
    conditions: "{{ item.conditions | default(omit) }}"
    esc_period: "{{ item.esc_period | default(omit) }}"
    eval_type: "{{ item.eval_type | default(omit) }}"
    event_source: "{{ item.event_source | default(omit) }}"
    formula: "{{ item.formula | default(omit) }}"
    operations: "{{ item.operations | default(omit) }}"
    pause_in_maintenance: "{{ item.pause_in_maintenance | default(omit) }}"
    recovery_operations: "{{ item.recovery_operations | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    status: "{{ item.status | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
  loop: "{{ zabbix_config_actions }}"
  tags:
    - zabbix_config_actions

- name: Manage web scenarios
  zabbix_webscenario:
    server_url: "{{ zabbix_config_server_url }}"
    login_user: "{{ zabbix_config_login_user }}"
    login_password: "{{ zabbix_config_login_password }}"
    name: "{{ item.name }}"
    host_name: "{{ item.host_name }}"
    steps: "{{ item.steps | default(omit) }}"
    agent: "{{ item.agent | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    delay: "{{ item.delay | default(omit) }}"
    headers: "{{ item.headers | default(omit) }}"
    retries: "{{ item.retries | default(omit) }}"
  loop: "{{ zabbix_config_web_scenarios }}"
  tags:
    - zabbix_config_web_scenarios

- name: Manage media types
  community.zabbix.zabbix_mediatype:
    server_url: "{{ zabbix_config_server_url }}"
    login_user: "{{ zabbix_config_login_user }}"
    login_password: "{{ zabbix_config_login_password }}"
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    attempt_interval: "{{ item.attempt_interval | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    max_attempts: "{{ item.max_attempts | default(omit) }}"
    max_sessions: "{{ item.max_sessions | default(omit) }}"
    message_templates: "{{ item.message_templates | default(omit) }}"
    process_tags: "{{ item.process_tags | default(omit) }}"
    script_name: "{{ item.script_name | default(omit) }}"
    script_params: "{{ item.script_params | default(omit) }}"
    smtp_authentication: "{{ item.smtp_authentication | default(omit) }}"
    smtp_email: "{{ item.smtp_email | default(omit) }}"
    smtp_helo: "{{ item.smtp_helo | default(omit) }}"
    smtp_security: "{{ item.smtp_security | default(omit) }}"
    smtp_server: "{{ item.smtp_server | default(omit) }}"
    smtp_server_port: "{{ item.smtp_server_port | default(omit) }}"
    smtp_verify_host: "{{ item.smtp_verify_host | default(omit) }}"
    smtp_verify_peer: "{{ item.smtp_verify_peer | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    username: "{{ item.username | default(omit) }}"
    webhook_params: "{{ item.webhook_params | default(omit) }}"
    webhook_script: "{{ item.webhook_script | default(omit) }}"
    webhook_timeout: "{{ item.webhook_timeout | default(omit) }}"
  loop: "{{ zabbix_config_media_types }}"
  tags:
    - zabbix_config_media_types

- name: Manage user groups
  community.zabbix.zabbix_usergroup:
    server_url: "{{ zabbix_config_server_url }}"
    login_user: "{{ zabbix_config_login_user }}"
    login_password: "{{ zabbix_config_login_password }}"
    name: "{{ item.name }}"
    debug_mode: "{{ item.debug_mode | default(omit) }}"
    gui_access: "{{ item.gui_access | default(omit) }}"
    rights: "{{ item.rights | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    status: "{{ item.status | default(omit) }}"
    tag_filters: "{{ item.tag_filters | default(omit) }}"
  loop: "{{ zabbix_config_usergroups }}"
  tags:
    - zabbix_config_usergroups

- name: Manage users
  community.zabbix.zabbix_user:
    server_url: "{{ zabbix_config_server_url }}"
    login_user: "{{ zabbix_config_login_user }}"
    login_password: "{{ zabbix_config_login_password }}"
    alias: "{{ item.alias }}"
    after_login_url: "{{ item.after_login_url | default(omit) }}"
    autologin: "{{ item.autologin | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    override_passwd: "{{ item.override_passwd | default(omit) }}"
    passwd: "{{ item.passwd | default(omit) }}"
    refresh: "{{ item.refresh | default(omit) }}"
    role_name: "{{ item.role_name | default(omit) }}"
    rows_per_page: "{{ item.rows_per_page | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    surname: "{{ item.surname | default(omit) }}"
    theme: "{{ item.theme | default(omit) }}"
    timezone: "{{ item.timezone | default(omit) }}"
    user_medias: "{{ item.user_medias | default(omit) }}"
    usrgrps: "{{ item.usrgrps | default(omit) }}"
  loop: "{{ zabbix_config_users }}"
  tags:
    - zabbix_config_users
