---
- name: Manage templates
  community.zabbix.zabbix_template:
    server_url: "{{ zabbix_config_server_url }}"
    login_user: "{{ zabbix_config_login_user }}"
    login_password: "{{ zabbix_config_login_password }}"
    clear_templates: "{{ item.clear_templates | default(omit) }}"
    dump_format: "{{ item.dump_format | default(omit) }}"
    link_templates: "{{ item.link_templates | default(omit) }}"
    macros: "{{ item.macros | default(omit) }}"
    omit_date: "{{ item.omit_date | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    template_groups: "{{ item.template_groups | default(omit) }}"
    template_json: "{{ item.template_json | default(omit) }}"
    template_name: "{{ item.template_name | default(omit) }}"
    template_xml: "{{ item.template_xml | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
  loop: "{{ zabbix_config_templates }}"

- name: Create host groups
  community.zabbix.zabbix_group:
    server_url: "{{ zabbix_config_server_url }}"
    login_user: "{{ zabbix_config_login_user }}"
    login_password: "{{ zabbix_config_login_password }}"
    state: present
    host_groups: "{{ item }}"
  loop: "{{ zabbix_config_host_groups }}"

- name: Manage hosts
  community.zabbix.zabbix_host:
    description: "{{ item.description | default(omit) }}"
    host_groups: "{{ item.host_groups | default(omit) }}"
    host_name: "{{ item.host_name }}"
    interfaces: "{{ item.interfaces | default(omit) }}"
    link_templates: "{{ item.link_templates | default(omit) }}"
    login_password: "{{ zabbix_config_login_password }}"
    login_user: "{{ zabbix_config_login_user }}"
    macros: "{{ item.macros | default(omit) }}"
    server_url: "{{ zabbix_config_server_url }}"
    state: "{{ item.state | default(omit) }}"
    status: "{{ item.status | default(omit) }}"
    tags: "{{ item.tags | default(omit) }}"
    visible_name: "{{ item.visible_name | default(omit) }}"
  loop: "{{ zabbix_config_hosts }}"

- name: Manage actions
  community.zabbix.zabbix_action:
    server_url: "{{ zabbix_config_server_url }}"
    login_user: "{{ zabbix_config_login_user }}"
    login_password: "{{ zabbix_config_login_password }}"
    name: "{{ item.name }}"
    conditions: "{{ item.conditions | default(omit) }}"
    esc_period: "{{ item.esc_period | default(omit) }}"
    eval_type: "{{ item.eval_type | default(omit) }}"
    event_source: "{{ item,event_source | default(omit) }}"
    formula: "{{ item.formula | default(omit) }}"
    operations: "{{ item.operations | default(omit) }}"
    pause_in_maintenance: "{{ item.pause_in_maintenance | default(omit) }}"
    recovery_operations: "{{ item.recovery_operations | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    status: "{{ item.status | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
  loop: "{{ zabbix_config_actions }}"

- name: Manage web scenarios
  zabbix_webscenario:
    server_url: "{{ zabbix_config_server_url }}"
    login_user: "{{ zabbix_config_login_user }}"
    login_password: "{{ zabbix_config_login_password }}"
    name: "{{ item.name }}"
    host_name: "{{ item.host_name }}"
    steps: "{{ item.steps | default(omit) }}"
    agent: "{{ item.agent | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    delay: "{{ item.delay | default(omit) }}"
    headers: "{{ item.headers | default(omit) }}"
    retries: "{{ item.retries | default(omit) }}"
  loop: "{{ zabbix_config_web_scenarios }}"

- name: Manage media types
  community.zabbix.zabbix_mediatype:
    server_url: "{{ zabbix_config_server_url }}"
    login_user: "{{ zabbix_config_login_user }}"
    login_password: "{{ zabbix_config_login_password }}"
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    attempt_interval: "{{ item.attempt_interval | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    max_attempts: "{{ item.max_attempts | default(omit) }}"
    max_sessions: "{{ item.max_sessions | default(omit) }}"
    message_templates: "{{ item.message_templates | default(omit) }}"
    process_tags: "{{ item.process_tags | default(omit) }}"
    script_name: "{{ item.script_name | default(omit) }}"
    script_params: "{{ item.script_params | default(omit) }}"
    smtp_authentication: "{{ item.smtp_authentication | default(omit) }}"
    smtp_email: "{{ item.smtp_email | default(omit) }}"
    smtp_helo: "{{ item.smtp_helo | default(omit) }}"
    smtp_security: "{{ item.smtp_security | default(omit) }}"
    smtp_server: "{{ item.smtp_server | default(omit) }}"
    smtp_server_port: "{{ item.smtp_server_port | default(omit) }}"
    smtp_verify_host: "{{ item.smtp_verify_host | default(omit) }}"
    smtp_verify_peer: "{{ item.smtp_verify_peer | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    username: "{{ item.username | default(omit) }}"
    webhook_params: "{{ item.webhook_params | default(omit) }}"
    webhook_script: "{{ item.webhook_script | default(omit) }}"
    webhook_timeout: "{{ item.webhook_timeout | default(omit) }}"
  loop: "{{ zabbix_config_media_types }}"
