---
name: Ansible Lint

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint Ansible Role
      uses: ansible-community/ansible-lint-action@v6.0.2
      # optional:
      # with:
      #  args: "" # args to pass to ansible-lint command
